# Generated by Django 3.1.7 on 2021-05-18 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('621ced02-bd62-4910-adcb-656f318d7f2e'), primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('quandity', models.PositiveIntegerField()),
            ],
        ),
    ]
