# Generated by Django 3.1.7 on 2021-05-18 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210518_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c95fab0-b6fe-4dd4-bf17-c6d5dc3fcb77'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
