# Generated by Django 3.1.7 on 2021-05-18 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210518_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64a65441-6fb6-40fb-8568-d44e173fccd9'), primary_key=True, serialize=False),
        ),
    ]
