# Generated by Django 3.1.7 on 2021-05-18 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210518_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad58b11b-e952-4ff9-bbc1-743ced64e8b8'), primary_key=True, serialize=False),
        ),
    ]
