# Generated by Django 3.2.3 on 2021-05-21 12:24

from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210518_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a22ee9d-7f48-47c3-832b-256217eed106'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='images/'),
        ),
    ]
