# Generated by Django 3.2.3 on 2021-05-21 12:31

from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210521_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7256d1ef-3ef9-4f3a-9785-dca36949bb6f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[5000, 3000], upload_to='images/'),
        ),
    ]
