# Generated by Django 3.2.3 on 2021-05-21 12:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=[3000, 5000], force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='images/'),
        ),
    ]
